services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo
    command: npm start 
    
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      ME_CONFIG_BASICAUTH: true
volumes:
  mongo-data: